kind: Service
apiVersion: v1
metadata:
  name: test-service-a
spec:
  type: NodePort # when run with minikube
  selector:
    app: test-service-a
    role: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080