kind: Service
apiVersion: v1
metadata:
  name: test-service-a
spec:
  type: NodePort # when run with minikube
  selector:
    app: test-service-a
    role: backend
  ports:
    - name: http-spring
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-vertx
      protocol: TCP
      port: 8081
      targetPort: 8081


---

kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
  clusterIP: None