kind: Service
apiVersion: v1
metadata:
  name: test-service-a
spec:
  type: NodePort # when run with minikube
  selector:
    app: test-service-a
    role: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    role: db
  ports:
    - name: mysql
      protocol: TCP
      port: 3310
      targetPort: 3310